# Generated by Django 3.1.3 on 2020-12-19 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='claseHabitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habitacionIdentificador', models.CharField(max_length=10)),
                ('habitacionMetros', models.DecimalField(decimal_places=2, max_digits=2)),
                ('habitacionCama', models.CharField(choices=[('1', '90x190'), ('2', '105x190'), ('3', '135x190'), ('4', '150x190'), ('5', '2 (90x190)')], default='1', max_length=1)),
                ('habitacionTipo', models.CharField(choices=[('INT', 'Interior'), ('EXT', 'Exterior')], default='INT', max_length=3)),
                ('habitacionUso', models.CharField(choices=[('INT', 'Interior'), ('EXT', 'Exterior')], default='INT', max_length=3)),
                ('habitacionFechaDeAlta', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['habitacionIdentificador'],
            },
        ),
    ]
