# Generated by Django 3.1.3 on 2020-12-19 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasehabitacion',
            name='habitacionAscensor',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clasehabitacion',
            name='habitacionAseos',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clasehabitacion',
            name='habitacionBalcon',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clasehabitacion',
            name='habitacionBanos',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clasehabitacion',
            name='habitacionVentanas',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clasehabitacion',
            name='habitacionUso',
            field=models.CharField(choices=[('IND', 'Individual'), ('DOB', 'Doble')], default='INT', max_length=3),
        ),
    ]
