# Generated by Django 3.1.3 on 2021-01-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0002_auto_20201220_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasehabitacion',
            name='habitacionIdentificador',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='clasehabitacion',
            name='habitacionMetros',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='clasehabitacion',
            name='habitacionUso',
            field=models.CharField(choices=[('IND', 'Individual'), ('DOB', 'Doble')], default='IND', max_length=3),
        ),
    ]
