# Generated by Django 3.1.3 on 2021-08-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0004_claseapartamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasehabitacion',
            name='habitacionOcupacion',
            field=models.TextField(default='#'),
            preserve_default=False,
        ),
    ]
