# Generated by Django 3.1.3 on 2021-09-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0005_clasehabitacion_habitacionocupacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='claseVariables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varCalculadoraTipoExt', models.DecimalField(decimal_places=2, max_digits=4)),
                ('varCalculadoraTipoInt', models.DecimalField(decimal_places=2, max_digits=4)),
                ('varCalculadoraUsoInd', models.DecimalField(decimal_places=2, max_digits=4)),
                ('varCalculadoraUsoDob', models.DecimalField(decimal_places=2, max_digits=4)),
                ('varCalculadoraHab4', models.DecimalField(decimal_places=2, max_digits=4)),
                ('varCalculadoraHab5', models.DecimalField(decimal_places=2, max_digits=4)),
                ('varCalculadoraHab6', models.DecimalField(decimal_places=2, max_digits=4)),
                ('varCalculadoraHab7', models.DecimalField(decimal_places=2, max_digits=4)),
                ('varCalculadoraHab8', models.DecimalField(decimal_places=2, max_digits=4)),
                ('varCalculadoraHabPlus', models.DecimalField(decimal_places=2, max_digits=4)),
                ('varCalculadoraBalSi', models.DecimalField(decimal_places=2, max_digits=4)),
                ('varCalculadoraBalNo', models.DecimalField(decimal_places=2, max_digits=4)),
                ('varCalculadoraAscSi', models.DecimalField(decimal_places=2, max_digits=4)),
                ('varCalculadoraAscNo', models.DecimalField(decimal_places=2, max_digits=4)),
                ('varCalculadoraCama90', models.DecimalField(decimal_places=2, max_digits=4)),
                ('varCalculadoraCama105', models.DecimalField(decimal_places=2, max_digits=4)),
                ('varCalculadoraCama135', models.DecimalField(decimal_places=2, max_digits=4)),
                ('varCalculadoraCama150', models.DecimalField(decimal_places=2, max_digits=4)),
                ('varCalculadoraCama2x90', models.DecimalField(decimal_places=2, max_digits=4)),
                ('varCalculadoraZona1', models.DecimalField(decimal_places=2, max_digits=4)),
                ('varCalculadoraZona2', models.DecimalField(decimal_places=2, max_digits=4)),
                ('varCalculadoraZona3', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'ordering': ['varCalculadoraTipoInt'],
            },
        ),
    ]
