# Generated by Django 3.1.3 on 2021-10-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0006_clasevariables'),
    ]

    operations = [
        migrations.CreateModel(
            name='clasereserva',
            fields=[
                ('reservaId', models.AutoField(primary_key=True, serialize=False)),
                ('demandaId', models.IntegerField(max_length=10)),
                ('reservaContacto', models.CharField(max_length=10)),
                ('reservaComercial', models.CharField(max_length=10)),
                ('reservaApartamento', models.CharField(max_length=5)),
                ('reservaHabitacion', models.CharField(max_length=12)),
                ('reservaFRegistro', models.DateTimeField()),
                ('reservaFEntrada', models.DateTimeField(null=True)),
                ('reservaFSalida', models.DateTimeField(null=True)),
                ('reservaFPago', models.DateTimeField(null=True)),
                ('reservaFormaPago', models.CharField(choices=[('1', 'Efectivo'), ('2', 'Tarjeta'), ('3', 'Transferencia')], default='1', max_length=3)),
                ('reservaTipoPago', models.CharField(choices=[('1', 'Único'), ('2', 'Mensual'), ('3', 'Trimestral')], default='1', max_length=3)),
                ('reservaObservaciones', models.CharField(max_length=200)),
                ('reservaHistAcciones', models.CharField(max_length=10000)),
            ],
            options={
                'ordering': ['reservaFRegistro'],
            },
        ),
        migrations.AlterModelOptions(
            name='clasevariables',
            options={'ordering': []},
        ),
    ]
