# Generated by Django 3.1.3 on 2021-10-10 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0007_auto_20211010_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clasereserva',
            name='demandaId',
        ),
    ]
