# Generated by Django 3.1.3 on 2021-10-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0009_clasereserva_demandaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasereserva',
            name='reservaTipoPago',
            field=models.CharField(choices=[('1', 'Único'), ('2', 'Mensual'), ('3', 'Trimestral'), ('4', 'Anual')], default='1', max_length=3),
        ),
    ]
