# Generated by Django 3.1.3 on 2021-11-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0010_auto_20211027_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='clasePagos',
            fields=[
                ('pagoId', models.AutoField(primary_key=True, serialize=False)),
                ('reservaId', models.IntegerField()),
                ('pagoFecha', models.DateTimeField()),
                ('pagoImporte', models.IntegerField(default=0)),
                ('pagoForma', models.CharField(choices=[('1', 'Efectivo'), ('2', 'Tarjeta'), ('3', 'Transferencia')], default='1', max_length=3)),
                ('pagoCompletado', models.BooleanField(default=False)),
                ('pagoPlazoTotal', models.IntegerField()),
                ('pagoPlazoActual', models.IntegerField()),
            ],
            options={
                'ordering': ['pagoId'],
            },
        ),
    ]
