# Generated by Django 3.1.3 on 2021-11-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0012_clasereserva_reservapago'),
    ]

    operations = [
        migrations.CreateModel(
            name='claseInquilinos',
            fields=[
                ('inquilinoId', models.AutoField(primary_key=True, serialize=False)),
                ('reservaId', models.IntegerField()),
                ('inquilinoNombre', models.CharField(max_length=100)),
                ('inquilinoApellidos', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['inquilinoId'],
            },
        ),
    ]
