# Generated by Django 3.1.3 on 2021-11-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0013_claseinquilinos'),
    ]

    operations = [
        migrations.CreateModel(
            name='claseCuentas',
            fields=[
                ('cuentaId', models.AutoField(primary_key=True, serialize=False)),
                ('reservaId', models.IntegerField()),
                ('cuentaNum', models.CharField(max_length=24)),
                ('cuentaTitular', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['cuentaId'],
            },
        ),
        migrations.CreateModel(
            name='claseTarjetas',
            fields=[
                ('tarjetaId', models.AutoField(primary_key=True, serialize=False)),
                ('reservaId', models.IntegerField()),
                ('tarjetaNum', models.IntegerField()),
                ('tarjetaAno', models.IntegerField()),
                ('tarjetaMes', models.IntegerField()),
                ('tarjetaCVV', models.IntegerField()),
                ('tarjetaTitular', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['tarjetaId'],
            },
        ),
        migrations.AddField(
            model_name='clasereserva',
            name='reservaCompletada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clasereserva',
            name='reservaIniciada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clasereserva',
            name='reservaFormaPago',
            field=models.CharField(choices=[('1', 'Efectivo'), ('2', 'Tarjeta'), ('3', 'Transferencia'), ('4', 'Domicialiación')], default='1', max_length=3),
        ),
    ]
