# Generated by Django 3.1.3 on 2021-11-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0014_auto_20211113_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='claseinquilinos',
            name='inquilinoDni',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='claseinquilinos',
            name='inquilinoTitular',
            field=models.BooleanField(default=False),
        ),
    ]
