# Generated by Django 3.1.3 on 2020-12-19 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='claseComercial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comercialNombre', models.CharField(max_length=20)),
                ('comercialApellido', models.CharField(max_length=40)),
                ('comercialDNI', models.CharField(max_length=10)),
                ('comercialFechaDeAlta', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['comercialApellido', '-comercialFechaDeAlta'],
            },
        ),
    ]
