# Generated by Django 3.1.3 on 2020-12-19 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='claseContacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactolNombre', models.CharField(max_length=20)),
                ('contactoApellido', models.CharField(max_length=40)),
                ('contactoEmail', models.CharField(max_length=50)),
                ('contactoTelefono', models.CharField(max_length=9)),
                ('contactoDNI', models.CharField(max_length=10)),
                ('contactoFechaDeAlta', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['contactoApellido', '-contactoFechaDeAlta'],
            },
        ),
    ]
