# Generated by Django 3.1.3 on 2020-12-19 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_clasecontacto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clasecontacto',
            old_name='contactolNombre',
            new_name='contactoNombre',
        ),
    ]
