# Generated by Django 3.1.3 on 2021-03-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20201219_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='claseDemanda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demandaContacto', models.CharField(max_length=10)),
                ('demandaComercial', models.CharField(max_length=10)),
                ('demandaApartamento', models.CharField(max_length=5)),
                ('demandaFRegistro', models.DateTimeField(auto_now_add=True)),
                ('demandaFAsignacion', models.DateTimeField()),
                ('demandaFVisita', models.DateTimeField()),
                ('demandaFOferta', models.DateTimeField()),
                ('demandaFCierre', models.DateTimeField()),
                ('demandaObservaciones', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['demandaFRegistro'],
            },
        ),
    ]
