# Generated by Django 3.1.3 on 2021-03-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_clasedemanda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasedemanda',
            name='demandaFAsignacion',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='clasedemanda',
            name='demandaFCierre',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='clasedemanda',
            name='demandaFOferta',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='clasedemanda',
            name='demandaFVisita',
            field=models.DateTimeField(null=True),
        ),
    ]
