# Generated by Django 3.1.3 on 2021-03-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20210330_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clasedemanda',
            name='id',
        ),
        migrations.AddField(
            model_name='clasedemanda',
            name='demandaId',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clasedemanda',
            name='demandaFRegistro',
            field=models.DateTimeField(),
        ),
    ]
