# Generated by Django 3.1.3 on 2021-04-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20210330_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasedemanda',
            name='demandaHabitacion',
            field=models.CharField(default=None, max_length=12),
            preserve_default=False,
        ),
    ]
