# Generated by Django 3.1.3 on 2021-07-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_clasedemanda_demandahabitacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasedemanda',
            name='demandaHistAcciones',
            field=models.CharField(default=0, max_length=10000),
            preserve_default=False,
        ),
    ]
