# Generated by Django 3.1.3 on 2021-08-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_clasedemanda_demandahistacciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasedemanda',
            name='demandaFEntrada',
            field=models.DateTimeField(default='1900-01-01 00:00'),
        ),
        migrations.AddField(
            model_name='clasedemanda',
            name='demandaFSalida',
            field=models.DateTimeField(default='1900-01-01 00:00'),
        ),
    ]
