# Generated by Django 3.1.3 on 2021-08-18 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_auto_20210818_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clasedemanda',
            name='demandaFEntrada',
        ),
        migrations.RemoveField(
            model_name='clasedemanda',
            name='demandaFSalida',
        ),
    ]
