# Generated by Django 3.1.3 on 2021-08-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_auto_20210818_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasedemanda',
            name='demandaFEntrada',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='clasedemanda',
            name='demandaFSalida',
            field=models.DateTimeField(null=True),
        ),
    ]
