# Generated by Django 3.1.3 on 2021-08-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_auto_20210818_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasedemanda',
            name='demandaOfeObservaciones',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clasedemanda',
            name='demandaVisObservaciones',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
