# Generated by Django 3.1.3 on 2021-08-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_auto_20210823_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clasedemanda',
            name='demandaOfeObservaciones',
        ),
        migrations.AddField(
            model_name='clasedemanda',
            name='demandaOferta',
            field=models.IntegerField(default=0),
        ),
    ]
