# Generated by Django 3.1.3 on 2021-08-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_auto_20210823_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasedemanda',
            name='demandaGanada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clasedemanda',
            name='demandaPerdida',
            field=models.BooleanField(default=False),
        ),
    ]
