# Generated by Django 3.1.3 on 2021-09-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_auto_20210824_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasecomercial',
            name='comercialActivo',
            field=models.BooleanField(default=True),
        ),
    ]
